cookietemple_version: "1.3.11 # <<COOKIETEMPLE_NO_BUMP>>"
domain: lib
language: cpp
project_slug: iterator_facade
project_slug_no_hyphen: iterator_facade
template_version: "1.1.2 # <<COOKIETEMPLE_NO_BUMP>>"
template_handle: lib-cpp
github_username: dkavolis
creator_github_username: dkavolis
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Daumantas Kavolis
email: daumantas.kavolis@gmail.com
project_name: iterator_facade
project_short_description: iterator_facade for C++20
version: 0.1.0
license: CC0
