name: linux

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: ubuntu-20.04
    name: ${{ github.workflow }}-${{ matrix.cxx }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - cxx: g++-11
            install: sudo apt install g++-11
          - install: |
              sudo apt install clang-12
            #  sudo apt install libc++-12-dev libc++abi-12-dev
            # libc++ provides <concepts> from 13.0 only
            # cxxflags: -stdlib=libc++
            cxx: clang++-12

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Find the number of threads (Linux)
        run: echo "::set-output name=THREADS::`nproc`"
        id: number-of-threads
        shell: bash

      - uses: ./.github/build
        with:
          cmakePreset: ci-linux
          cxx: ${{ matrix.cxx }}
          install: ${{ matrix.install }}
          cxxflags: ${{ matrix.cxxflags }}
          threads: ${{ steps.number-of-threads.outputs.THREADS }}
