name: macos

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: macos-11
    name: ${{ github.workflow }}-${{ matrix.cxx }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        include:
          - cxx: g++-11
          - cxx: clang++
            # cxxflags: -stdlib=libc++

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Find the number of threads (macOS)
        run: echo "::set-output name=THREADS::`sysctl -n hw.logicalcpu`"
        id: number-of-threads
        shell: bash

      - uses: ./.github/build
        with:
          cmakePreset: ci-linux
          cxx: ${{ matrix.cxx }}
          cxxflags: ${{ matrix.cxxflags }}
          threads: ${{ steps.number-of-threads.outputs.THREADS }}
