name: macos

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: macos-11
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Find the number of threads (macOS)
        run: echo "::set-output name=THREADS::`sysctl -n hw.logicalcpu`"
        id: number-of-threads
        shell: bash

      - uses: ./.github/build
        with:
          cmakePreset: ci-linux
          cxx: g++-11
          threads: ${{ steps.number-of-threads.outputs.THREADS }}
